name: ci
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python
    steps:
      - uses: actions/checkout@v2
      - run: pip install tox
      - run: tox --notest
      - run: tox -e py38

  lint:
    runs-on: ubuntu-latest
    container: python
    steps:
      - uses: actions/checkout@v2
      - run: pip install tox
      - run: tox --notest
      - run: tox -e flake8
